"""SGLang-native proxy for exact token-in / token-out capture.

Provides two components for intercepting black-box agent LLM calls and
capturing exact token-level trajectory data for RL training:

1. ModelInterceptProxy - aiohttp proxy server that intercepts agent API calls,
   routes them to the SGLang ``/generate`` endpoint with exact ``input_ids``,
   and records ``CapturedTurn`` data for each request.
2. CapturedTurn - dataclass holding the exact token IDs and log-probs for one
   request/response pair, with no decode/re-encode approximation.

Request / response flow per agent turn
---------------------------------------
    claude-code (Anthropic SDK)
        │  POST /v1/messages   (Anthropic format, may request SSE)
        ▼
    ModelInterceptProxy  ← this module
        1. _anthropic_to_openai_messages()  – mirror SGLang's Anthropic→OpenAI conversion
        2. tokenizer.apply_chat_template(…, tokenize=True)  – get exact input_ids
        3. POST /generate to SGLang with input_ids + return_logprob=True
        4. extract output_ids from top-level field; log_probs from output_token_logprobs
        5. _parse_qwen3_output()  – decode output text → Anthropic content blocks
        6. store CapturedTurn(input_ids, output_ids, log_probs, …)
        7. return Anthropic SSE stream or plain JSON response to claude-code
        │
        ▼
    SGLang model server  (processes exactly input_ids, returns output_ids)

Token-in / token-out guarantee
--------------------------------
``_accumulated_ids`` is maintained as exact running state across turns:
- Turn 0   : ``apply_chat_template(initial_messages)``
- After gen : ``_accumulated_ids += output_ids``  (no decode/re-encode)
- Between  : tool-result delta computed via stub method (no round-trip)

``_build_token_arrays`` in ``generate_with_harbor.py`` is therefore a trivial
concatenation — no ``apply_chat_template`` approximation needed there.
"""

import json
import logging
import re
import uuid
from dataclasses import dataclass
from typing import Any

import aiohttp
from aiohttp import web

logger = logging.getLogger(__name__)


# =============================================================================
# CapturedTurn
# =============================================================================


@dataclass
class CapturedTurn:
    """One request / response pair with exact token-level information.

    ``input_ids`` and ``output_ids`` are the actual token IDs processed and
    generated by SGLang — not reconstructed from text.  ``log_probs`` is
    aligned element-wise with ``output_ids``.
    """

    # Raw Anthropic-format request fields (for trajectory matching / inspection)
    messages: list[dict[str, Any]]
    system: str | list | None

    # Exact token IDs — no approximation
    input_ids: list[int]    # tokens fed to the model this turn (includes gen prompt)
    output_ids: list[int]   # tokens the model generated
    log_probs: list[float]  # per-output-token log prob; len == len(output_ids)

    # Decoded response returned to claude-code
    response_content: list[dict[str, Any]]
    stop_reason: str = "end_turn"


# =============================================================================
# Anthropic → HuggingFace message conversion
# =============================================================================


def _anthropic_to_openai_messages(
    system: Any,
    messages: list[dict],
) -> list[dict]:
    """Convert Anthropic system + messages to OpenAI chat format.

    Mirrors SGLang's ``AnthropicServing._convert_to_chat_completion_request``
    (sglang/srt/entrypoints/anthropic/serving.py) exactly so that
    ``apply_chat_template`` on the result produces the same ``input_ids``
    as SGLang's internal ``_convert_to_internal_request``.

    Key rules (matching SGLang):
    - system str/list          → {"role": "system", "content": str}
    - user tool_result blocks  → one {"role": "tool", ...} message each
    - assistant tool_use       → {"tool_calls": [...]} on the assistant message
    - assistant single text    → content is a plain string (not a list)
    - assistant multi-block    → content is a list of {"type": "text", ...} dicts
    """
    openai: list[dict] = []

    # System prompt
    if system:
        if isinstance(system, str):
            openai.append({"role": "system", "content": system})
        elif isinstance(system, list):
            parts = [b.get("text", "") for b in system
                     if isinstance(b, dict) and b.get("type") == "text"]
            openai.append({"role": "system", "content": "\n".join(parts)})

    for msg in messages:
        role = msg.get("role", "")
        content = msg.get("content", "")

        if isinstance(content, str):
            openai.append({"role": role, "content": content})
            continue

        # Complex content (list of blocks)
        openai_msg: dict = {"role": role}
        content_parts: list[dict] = []
        tool_calls: list[dict] = []

        for block in content:
            if not isinstance(block, dict):
                continue
            btype = block.get("type", "")

            if btype == "text" and block.get("text"):
                content_parts.append({"type": "text", "text": block["text"]})

            elif btype == "tool_use":
                tool_calls.append({
                    "id": block.get("id") or f"call_{uuid.uuid4().hex}",
                    "type": "function",
                    "function": {
                        "name": block.get("name", ""),
                        "arguments": json.dumps(block.get("input") or {}),
                    },
                })

            elif btype == "tool_result" and role == "user":
                # Each tool_result becomes a separate role=tool message —
                # append immediately and skip the normal openai_msg path.
                inner = block.get("content", "")
                if isinstance(inner, list):
                    text_parts = [b.get("text", "") for b in inner
                                  if isinstance(b, dict) and b.get("type") == "text"]
                    # Always flatten to a plain string: apply_chat_template
                    # requires role=tool content to be a str, not a list.
                    tool_content: str = "\n".join(text_parts)
                else:
                    tool_content = str(inner) if inner else ""
                openai.append({
                    "role": "tool",
                    "tool_call_id": block.get("tool_use_id") or block.get("id") or "",
                    "content": tool_content,
                })

        if tool_calls:
            openai_msg["tool_calls"] = tool_calls

        if content_parts:
            # Simplify to a plain string when there is exactly one text block
            # (matches SGLang line 240-243 in serving.py)
            if len(content_parts) == 1 and content_parts[0]["type"] == "text":
                openai_msg["content"] = content_parts[0]["text"]
            else:
                openai_msg["content"] = content_parts
        elif not tool_calls:
            continue  # empty message — skip (matches SGLang line 244-245)

        openai.append(openai_msg)

    return openai


def _anthropic_tools_to_openai(tools: list[dict]) -> list[dict]:
    """Convert Anthropic tool definitions to OpenAI function format.

    Mirrors SGLang's tool conversion (serving.py lines 273-286).

    Anthropic:  {"name": ..., "description": ..., "input_schema": {...}}
    OpenAI:     {"type": "function", "function": {"name": ..., "description": ...,
                                                   "parameters": {...}}}
    """
    return [
        {
            "type": "function",
            "function": {
                "name": t.get("name", ""),
                "description": t.get("description", ""),
                "parameters": t.get("input_schema", {}),
            },
        }
        for t in tools
    ]


# =============================================================================
# Qwen3 native output parser
# =============================================================================

_THINK_RE = re.compile(r"<think>\s*(.*?)\s*</think>", re.DOTALL)
_TOOL_CALL_RE = re.compile(r"<tool_call>\s*(.*?)\s*</tool_call>", re.DOTALL)
# Hermes-style: <function=NAME><parameter=KEY>VALUE</parameter>…</function>
_FUNCTION_RE = re.compile(
    r"<function=(\w+)>(.*?)</function>", re.DOTALL
)
_PARAM_RE = re.compile(r"<parameter=(\w+)>(.*?)</parameter>", re.DOTALL)


def _parse_qwen3_output(text: str) -> tuple[list[dict[str, Any]], str]:
    """Parse Qwen3 native generation into Anthropic content blocks.

    Handles two tool-call formats that Qwen3-Coder may produce:

    Format A — JSON wrapped in <tool_call> tags::

        <tool_call>
        {"name": "Read", "arguments": {"file_path": "/foo"}}
        </tool_call>

    Format B — Hermes-style XML function tags::

        <function=Read>
        <parameter=file_path>/foo</parameter>
        </function>

    Returns:
        (content_blocks, stop_reason)
        stop_reason is "tool_use" when at least one tool call was found,
        "end_turn" otherwise.
    """
    content_blocks: list[dict] = []
    remaining = text

    # Extract <think> blocks first
    for m in _THINK_RE.finditer(text):
        content_blocks.append({"type": "thinking", "thinking": m.group(1)})
        remaining = remaining.replace(m.group(0), "", 1)

    parsed_tool_calls: list[tuple[str, dict]] = []

    # Format A: <tool_call>…</tool_call>
    # The body is either plain JSON  {"name": …, "arguments": {…}}
    # or contains a nested <function=NAME> block (Hermes style inside tool_call).
    # Either way the whole <tool_call>…</tool_call> is consumed from remaining.
    for m in _TOOL_CALL_RE.finditer(remaining):
        body = m.group(1)
        payload: dict | None = None
        try:
            payload = json.loads(body)
        except json.JSONDecodeError:
            # Try nested <function=NAME><parameter=…>…</parameter></function>
            fm = _FUNCTION_RE.search(body)
            if fm:
                name = fm.group(1)
                args: dict = {}
                for pm in _PARAM_RE.finditer(fm.group(2)):
                    args[pm.group(1)] = pm.group(2).strip()
                payload = {"name": name, "arguments": args}
            else:
                logger.warning("Failed to parse tool_call body: %s", body[:200])
        # Always remove the <tool_call> block from remaining (even on parse failure)
        # so it does not bleed into the plain-text block and confuse the agent.
        remaining = remaining.replace(m.group(0), "", 1)
        if payload:
            parsed_tool_calls.append((m.group(0), payload))

    # Format B: bare <function=NAME>…</function> outside any <tool_call> wrapper
    for m in _FUNCTION_RE.finditer(remaining):
        name = m.group(1)
        args = {}
        for pm in _PARAM_RE.finditer(m.group(2)):
            args[pm.group(1)] = pm.group(2).strip()
        parsed_tool_calls.append((m.group(0), {"name": name, "arguments": args}))
        remaining = remaining.replace(m.group(0), "", 1)

    # Remaining plain text
    plain = remaining.strip()
    if plain:
        content_blocks.append({"type": "text", "text": plain})

    # Append tool_use blocks in original order
    for idx, (_, payload) in enumerate(parsed_tool_calls, 1):
        args = payload.get("arguments", payload.get("parameters", {}))
        if isinstance(args, str):
            try:
                args = json.loads(args)
            except (json.JSONDecodeError, TypeError):
                pass
        content_blocks.append({
            "type": "tool_use",
            "id": f"toolu_{idx:04d}",
            "name": payload.get("name", ""),
            "input": args,
        })

    stop_reason = "tool_use" if parsed_tool_calls else "end_turn"
    return content_blocks, stop_reason


# =============================================================================
# SGLang /generate caller
# =============================================================================


async def _call_sglang_generate(
    sglang_url: str,
    input_ids: list[int],
    sampling_params: dict,
    routing_key: str | None = None,
) -> tuple[list[int], list[float], str, str]:
    """Call SGLang ``/generate`` with exact ``input_ids``.

    Args:
        sglang_url:      Base URL of the SGLang server, e.g. ``http://127.0.0.1:30000``.
        input_ids:       Token IDs to feed to the model.
        sampling_params: SGLang sampling_params dict (temperature, max_new_tokens, …).

    Returns:
        (output_ids, log_probs, stop_reason, output_text)
        ``output_ids`` and ``log_probs`` are aligned (same length).
    """
    payload = {
        "input_ids": input_ids,
        "sampling_params": sampling_params,
        "return_logprob": True,
        "logprob_start_len": 0,
    }

    headers = {}
    if routing_key:
        headers["X-SMG-Routing-Key"] = routing_key

    async with aiohttp.ClientSession() as session:
        async with session.post(
            f"{sglang_url}/generate",
            json=payload,
            headers=headers,
            timeout=aiohttp.ClientTimeout(total=600),
        ) as resp:
            if resp.status != 200:
                body = await resp.text()
                raise RuntimeError(
                    f"SGLang /generate returned {resp.status}: {body[:300]}"
                )
            data = await resp.json()

    output_text = data.get("text", "")
    meta = data.get("meta_info", {})

    # Prefer the top-level output_ids field (always present) over extracting
    # token IDs from output_token_logprobs (only present with return_logprob).
    output_ids: list[int] = [int(x) for x in (data.get("output_ids") or [])]

    token_logprobs: list = meta.get("output_token_logprobs") or []
    log_probs: list[float] = [float(item[0]) for item in token_logprobs]

    # If logprobs are shorter than output_ids (shouldn't happen, but be safe)
    if len(log_probs) < len(output_ids):
        log_probs.extend([0.0] * (len(output_ids) - len(log_probs)))

    finish_reason = meta.get("finish_reason", {})
    fr_type = finish_reason.get("type", "stop") if isinstance(finish_reason, dict) else str(finish_reason)
    stop_reason = {"stop": "end_turn", "length": "max_tokens"}.get(fr_type, "end_turn")

    return output_ids, log_probs, stop_reason, output_text


# =============================================================================
# Anthropic SSE emitter
# =============================================================================


def _anthropic_sse_events(
    msg_id: str,
    model: str,
    content_blocks: list[dict],
    stop_reason: str,
    input_tokens: int,
    output_tokens: int,
) -> list[bytes]:
    """Synthesise Anthropic SSE events from a complete response.

    claude-code requests streaming; we call SGLang non-streaming (needed to
    get the full ``output_token_logprobs`` in one shot) then re-emit as SSE.
    """
    events: list[str] = []

    def emit(event_type: str, data: dict) -> None:
        events.append(
            f"event: {event_type}\n"
            f"data: {json.dumps(data, ensure_ascii=False)}\n\n"
        )

    emit("message_start", {"type": "message_start", "message": {
        "id": msg_id, "type": "message", "role": "assistant",
        "content": [], "model": model, "stop_reason": None,
        "usage": {"input_tokens": input_tokens, "output_tokens": 0},
    }})

    for idx, block in enumerate(content_blocks):
        btype = block.get("type", "text")
        if btype == "text":
            emit("content_block_start", {"type": "content_block_start", "index": idx,
                  "content_block": {"type": "text", "text": ""}})
            emit("ping", {"type": "ping"})
            if block.get("text"):
                emit("content_block_delta", {"type": "content_block_delta", "index": idx,
                      "delta": {"type": "text_delta", "text": block["text"]}})
        elif btype == "tool_use":
            emit("content_block_start", {"type": "content_block_start", "index": idx,
                  "content_block": {"type": "tool_use", "id": block.get("id", ""),
                                    "name": block.get("name", ""), "input": {}}})
            emit("content_block_delta", {"type": "content_block_delta", "index": idx,
                  "delta": {"type": "input_json_delta",
                            "partial_json": json.dumps(block.get("input", {}))}})
        emit("content_block_stop", {"type": "content_block_stop", "index": idx})

    emit("message_delta", {"type": "message_delta",
          "delta": {"stop_reason": stop_reason, "stop_sequence": None},
          "usage": {"output_tokens": output_tokens}})
    emit("message_stop", {"type": "message_stop"})

    return [e.encode() for e in events]


# =============================================================================
# OpenAI response builders
# =============================================================================

_OPENAI_FINISH_REASON: dict[str, str] = {
    "end_turn":  "stop",
    "tool_use":  "tool_calls",
    "max_tokens": "length",
}


def _content_blocks_to_openai_message(content_blocks: list[dict]) -> dict:
    """Convert Anthropic content blocks to an OpenAI assistant message dict."""
    text = "\n".join(b.get("text", "") for b in content_blocks if b.get("type") == "text")
    tool_calls = [
        {
            "id": b.get("id", ""),
            "type": "function",
            "function": {
                "name": b.get("name", ""),
                "arguments": json.dumps(b.get("input", {}), ensure_ascii=False),
            },
        }
        for b in content_blocks if b.get("type") == "tool_use"
    ]
    msg: dict = {"role": "assistant", "content": text or None}
    if tool_calls:
        msg["tool_calls"] = tool_calls
    return msg


def _openai_sse_events(
    msg_id: str,
    model: str,
    content_blocks: list[dict],
    stop_reason: str,
    input_tokens: int,
    output_tokens: int,
) -> list[bytes]:
    """Synthesise OpenAI-format SSE chunks from a complete response."""
    finish_reason = _OPENAI_FINISH_REASON.get(stop_reason, "stop")
    chunk_base = {"id": msg_id, "object": "chat.completion.chunk", "model": model}
    events: list[bytes] = []

    def emit(data: dict) -> None:
        events.append(f"data: {json.dumps({**chunk_base, **data}, ensure_ascii=False)}\n\n".encode())

    # Opening chunk — role only
    emit({"choices": [{"index": 0, "delta": {"role": "assistant", "content": ""}, "finish_reason": None}]})

    # Text content
    text = "\n".join(b.get("text", "") for b in content_blocks if b.get("type") == "text")
    if text:
        emit({"choices": [{"index": 0, "delta": {"content": text}, "finish_reason": None}]})

    # Tool calls — one chunk per tool (name), then one chunk for arguments
    for i, b in enumerate(b for b in content_blocks if b.get("type") == "tool_use"):
        emit({"choices": [{"index": 0, "delta": {"tool_calls": [{"index": i, "id": b.get("id", ""),
              "type": "function", "function": {"name": b.get("name", ""), "arguments": ""}}]},
              "finish_reason": None}]})
        emit({"choices": [{"index": 0, "delta": {"tool_calls": [{"index": i, "function":
              {"arguments": json.dumps(b.get("input", {}), ensure_ascii=False)}}]},
              "finish_reason": None}]})

    # Final chunk with finish_reason and usage
    emit({"choices": [{"index": 0, "delta": {}, "finish_reason": finish_reason}],
          "usage": {"prompt_tokens": input_tokens, "completion_tokens": output_tokens,
                    "total_tokens": input_tokens + output_tokens}})
    events.append(b"data: [DONE]\n\n")
    return events


# =============================================================================
# Message content flattener
# =============================================================================


def _flatten_messages(messages: list[dict]) -> list[dict]:
    """Return a copy of messages with all content fields normalised to str.

    Qwen3's apply_chat_template concatenates role headers with content using
    Python string ``+``, so any content field that is a list (e.g. multi-block
    user messages from claude-code) raises ``TypeError: can only concatenate
    str (not "list") to str`` at line 98 of the Jinja template.

    We keep the original messages list intact and return a shallow copy with
    list content joined to plain text.
    """
    flattened = []
    for msg in messages:
        content = msg.get("content", "")
        if isinstance(content, list):
            parts = []
            for block in content:
                if not isinstance(block, dict):
                    parts.append(str(block))
                elif block.get("type") != "image_url":  # skip images; extract text from all other types
                    parts.append(block.get("text", ""))
            flat = {**msg, "content": "\n".join(p for p in parts if p)}
        else:
            flat = msg
        flattened.append(flat)
    return flattened


# =============================================================================
# ModelInterceptProxy
# =============================================================================


class ModelInterceptProxy:
    """Intercept agent API calls and capture exact token IDs via SGLang /generate.

    Routes incoming Anthropic (``/v1/messages``) or OpenAI
    (``/v1/chat/completions``) requests to the SGLang ``/generate`` endpoint
    using exact ``input_ids``, capturing ``CapturedTurn`` data for each turn.

    Architecture::

        claude-code  ──POST /v1/messages──►  ModelInterceptProxy
                     ◄── SSE / JSON ────────       │
                                                    │ POST /generate (input_ids)
                                                    ▼
                                              SGLang server
                                         (returns output_ids + logprobs)

    The proxy binds to ``0.0.0.0:{port}`` so Docker containers can reach it
    via the host IP.  Each concurrent trial gets its own port (managed by the
    port pool in ``generate_with_harbor.py``).

    Args:
        port:            TCP port to listen on.
        sglang_url:      Base URL of the SGLang server.
        tokenizer:       HuggingFace tokenizer with ``apply_chat_template``.
                         Must be the same tokenizer SGLang loaded at startup.
        sampling_params: SGLang-format sampling parameters forwarded verbatim
                         to ``/generate`` (temperature, max_new_tokens, …).
    """

    def __init__(
        self,
        port: int,
        sglang_url: str,
        tokenizer: Any,
        sampling_params: dict,
    ) -> None:
        self.port = port
        self.sglang_url = sglang_url.rstrip("/")
        self.tokenizer = tokenizer
        self.sampling_params = sampling_params
        self._captures: list[CapturedTurn] = []
        self._runner: web.AppRunner | None = None
        # Running exact token state — extended with raw output_ids after each
        # generation so the assistant response is NEVER decoded and re-encoded.
        self._accumulated_ids: list[int] | None = None
        self._prev_openai_msg_count: int = 0
        # Per-trial routing key — sent as X-SMG-Routing-Key so slime's
        # consistent-hashing router always maps all turns of this trial to
        # the same SGLang worker, enabling KV-cache prefix reuse.
        self._routing_key: str = str(uuid.uuid4())

    @property
    def captures(self) -> list[CapturedTurn]:
        return list(self._captures)

    def clear(self) -> None:
        self._captures.clear()
        self._accumulated_ids = None
        self._prev_openai_msg_count = 0

    async def start(self) -> None:
        app = web.Application()
        app.router.add_route("*", "/{path_info:.*}", self._handle)
        self._runner = web.AppRunner(app)
        await self._runner.setup()
        site = web.TCPSite(self._runner, "0.0.0.0", self.port)
        await site.start()
        logger.info(
            "ModelInterceptProxy :%d → %s (token-in/token-out via /generate)",
            self.port,
            self.sglang_url,
        )

    async def stop(self) -> None:
        if self._runner:
            await self._runner.cleanup()
            self._runner = None

    # ---- Request routing ----

    async def _handle(self, request: web.Request) -> web.StreamResponse:
        path = request.match_info.get("path_info", "")
        body_bytes = await request.read()
        try:
            body = json.loads(body_bytes) if body_bytes else {}
        except (json.JSONDecodeError, ValueError):
            body = {}

        if request.method == "POST" and "messages" in body:
            if "messages" in path:
                # Anthropic /v1/messages  (claude-code, opencode, …)
                return await self._handle_messages(request, body)
            if "chat/completions" in path:
                # OpenAI /v1/chat/completions  (aider, goose, swe-agent, …)
                return await self._handle_chat_completions(request, body)
        return await self._forward(request, path, body_bytes)

    # ---- Core intercept: /v1/messages → /generate → Anthropic response ----

    async def _handle_messages(
        self, request: web.Request, body: dict
    ) -> web.StreamResponse:
        system = body.get("system")
        messages = body.get("messages", [])
        tools_raw: list[dict] = body.get("tools") or []
        model: str = body.get("model", "")
        client_streaming: bool = bool(body.get("stream", False))

        # 1. Convert Anthropic → OpenAI format, mirroring SGLang's own
        #    AnthropicServing._convert_to_chat_completion_request().
        openai_messages = _anthropic_to_openai_messages(system, messages)
        openai_tools = _anthropic_tools_to_openai(tools_raw) if tools_raw else None

        # 2. Compute input_ids — strict token-in/token-out path.
        #
        #    First turn: apply_chat_template on the full initial messages.
        #    Subsequent turns: extend _accumulated_ids with the delta for only
        #    the NEW tool-result messages.  The assistant response from the
        #    previous turn was already appended as raw output_ids (no decode/
        #    re-encode), so _accumulated_ids is exact at every step.
        if self._accumulated_ids is None:
            tok_kwargs: dict = dict(
                tokenize=True,
                add_special_tokens=True,
                add_generation_prompt=True,
            )
            if openai_tools:
                tok_kwargs["tools"] = openai_tools
            # Defensive: apply_chat_template requires all content fields to be
            # strings (not lists) for non-multimodal models. Flatten any list
            # content to a plain string before calling the template.
            safe_messages = _flatten_messages(openai_messages)
            self._accumulated_ids = list(
                self.tokenizer.apply_chat_template(safe_messages, **tok_kwargs)
            )
        else:
            # new_messages = everything added since the last call.
            # This includes the ASSISTANT message from the previous turn
            # (already in _accumulated_ids as raw output_ids) PLUS the new
            # tool-result messages.  We must skip the assistant message.
            new_messages = openai_messages[self._prev_openai_msg_count:]
            new_tool_messages = [m for m in new_messages if m.get("role") != "assistant"]
            if new_tool_messages:
                tool_delta = self._compute_new_message_tokens(new_tool_messages, openai_tools)
                self._accumulated_ids = self._accumulated_ids + tool_delta

        input_ids: list[int] = self._accumulated_ids
        self._prev_openai_msg_count = len(openai_messages)

        # 3. Call SGLang /generate with input_ids directly — no re-tokenization.
        try:
            output_ids, log_probs, sglang_stop, output_text = (
                await _call_sglang_generate(
                    self.sglang_url, input_ids, self.sampling_params,
                    routing_key=self._routing_key,
                )
            )
        except Exception as exc:
            logger.error("SGLang /generate failed: %s", exc, exc_info=True)
            return web.Response(status=502, text=f"SGLang error: {exc}")

        # 4. Extend accumulated state with the exact generated tokens.
        #    This is the key step: output_ids are appended directly without
        #    any decode → parse → re-encode round-trip.
        self._accumulated_ids = self._accumulated_ids + list(output_ids)

        # 5. Parse Qwen3 native output → Anthropic content blocks.
        content_blocks, parsed_stop = _parse_qwen3_output(output_text)

        # Prefer SGLang's finish_reason for max_tokens; use parse-based for
        # end_turn vs tool_use (SGLang stop reason doesn't distinguish these).
        final_stop = "max_tokens" if sglang_stop == "max_tokens" else parsed_stop

        # 6. Store the captured turn with exact token IDs.
        msg_id = f"msg_{uuid.uuid4().hex[:24]}"
        self._captures.append(CapturedTurn(
            messages=messages,
            system=system,
            input_ids=input_ids,
            output_ids=output_ids,
            log_probs=log_probs,
            response_content=content_blocks,
            stop_reason=final_stop,
        ))

        # 7. Return Anthropic-format response to claude-code.
        anthropic_resp = {
            "id": msg_id,
            "type": "message",
            "role": "assistant",
            "content": content_blocks,
            "model": model,
            "stop_reason": final_stop,
            "stop_sequence": None,
            "usage": {
                "input_tokens": len(input_ids),
                "output_tokens": len(output_ids),
                "cache_creation_input_tokens": 0,
                "cache_read_input_tokens": 0,
            },
        }

        if client_streaming:
            sse_chunks = _anthropic_sse_events(
                msg_id, model, content_blocks, final_stop,
                len(input_ids), len(output_ids),
            )
            stream_resp = web.StreamResponse(status=200, headers={
                "Content-Type": "text/event-stream",
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
            })
            await stream_resp.prepare(request)
            for chunk in sse_chunks:
                await stream_resp.write(chunk)
            await stream_resp.write_eof()
            return stream_resp

        return web.Response(
            status=200,
            body=json.dumps(anthropic_resp, ensure_ascii=False).encode(),
            content_type="application/json",
        )

    # ---- OpenAI /v1/chat/completions intercept ----

    async def _handle_chat_completions(
        self, request: web.Request, body: dict
    ) -> web.StreamResponse:
        """Intercept OpenAI-format requests (aider, goose, swe-agent, …).

        Messages arrive already in OpenAI format so no Anthropic→OpenAI
        conversion is needed — they are passed directly to apply_chat_template.
        The same _accumulated_ids / stub-delta approach ensures exact token
        sequence continuity across turns.
        """
        messages: list[dict] = body.get("messages", [])
        tools_raw: list[dict] = body.get("tools") or []
        model: str = body.get("model", "")
        client_streaming: bool = bool(body.get("stream", False))

        openai_tools = tools_raw if tools_raw else None

        # 1. Compute input_ids — messages are already OpenAI format.
        if self._accumulated_ids is None:
            tok_kwargs: dict = dict(
                tokenize=True,
                add_special_tokens=True,
                add_generation_prompt=True,
            )
            if openai_tools:
                tok_kwargs["tools"] = openai_tools
            self._accumulated_ids = list(
                self.tokenizer.apply_chat_template(
                    _flatten_messages(messages), **tok_kwargs
                )
            )
        else:
            new_messages = messages[self._prev_openai_msg_count:]
            new_tool_messages = [m for m in new_messages if m.get("role") != "assistant"]
            if new_tool_messages:
                tool_delta = self._compute_new_message_tokens(new_tool_messages, openai_tools)
                self._accumulated_ids = self._accumulated_ids + tool_delta

        input_ids: list[int] = self._accumulated_ids
        self._prev_openai_msg_count = len(messages)

        # 2. Call SGLang /generate.
        try:
            output_ids, log_probs, sglang_stop, output_text = (
                await _call_sglang_generate(
                    self.sglang_url, input_ids, self.sampling_params,
                    routing_key=self._routing_key,
                )
            )
        except Exception as exc:
            logger.error("SGLang /generate failed: %s", exc, exc_info=True)
            return web.Response(status=502, text=f"SGLang error: {exc}")

        # 3. Extend accumulated state.
        self._accumulated_ids = self._accumulated_ids + list(output_ids)

        # 4. Parse output.
        content_blocks, parsed_stop = _parse_qwen3_output(output_text)
        final_stop = "max_tokens" if sglang_stop == "max_tokens" else parsed_stop

        # 5. Store captured turn.
        # System is the first message if its role is "system" (OpenAI convention).
        system = messages[0].get("content") if messages and messages[0].get("role") == "system" else None
        msg_id = f"chatcmpl_{uuid.uuid4().hex[:24]}"
        self._captures.append(CapturedTurn(
            messages=messages,
            system=system,
            input_ids=input_ids,
            output_ids=output_ids,
            log_probs=log_probs,
            response_content=content_blocks,
            stop_reason=final_stop,
        ))

        logger.debug(
            "Captured turn %d (OpenAI) | input_ids=%d output_ids=%d stop=%s",
            len(self._captures), len(input_ids), len(output_ids), final_stop,
        )

        # 6. Return OpenAI-format response.
        finish_reason = _OPENAI_FINISH_REASON.get(final_stop, "stop")
        oai_message = _content_blocks_to_openai_message(content_blocks)

        if client_streaming:
            sse_chunks = _openai_sse_events(
                msg_id, model, content_blocks, final_stop,
                len(input_ids), len(output_ids),
            )
            stream_resp = web.StreamResponse(status=200, headers={
                "Content-Type": "text/event-stream",
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
            })
            await stream_resp.prepare(request)
            for chunk in sse_chunks:
                await stream_resp.write(chunk)
            await stream_resp.write_eof()
            return stream_resp

        oai_resp = {
            "id": msg_id,
            "object": "chat.completion",
            "model": model,
            "choices": [{"index": 0, "message": oai_message, "finish_reason": finish_reason}],
            "usage": {
                "prompt_tokens": len(input_ids),
                "completion_tokens": len(output_ids),
                "total_tokens": len(input_ids) + len(output_ids),
            },
        }
        return web.Response(
            status=200,
            body=json.dumps(oai_resp, ensure_ascii=False).encode(),
            content_type="application/json",
        )

    # ---- Incremental tokenisation helper ----

    def _compute_new_message_tokens(
        self,
        new_messages: list[dict],
        tools: list[dict] | None,
    ) -> list[int]:
        """Return the token IDs for ``new_messages`` as a continuation delta.

        Uses a stub conversation ``[user_stub, asst_stub]`` to anchor the
        template, then subtracts it from the extended version.  The stub
        closes the previous assistant turn structurally so the new messages
        are formatted exactly as they would appear in context.

        Why this avoids the round-trip problem
        ---------------------------------------
        The only "new" content here is the tool-result text, which comes
        directly from the tool execution — it is never decoded from model
        output and re-encoded.  Therefore no JSON whitespace or key-order
        drift can occur.

        Why the stub works for any prefix-stable chat template
        -------------------------------------------------------
        For templates like Qwen3 where each message is formatted
        independently (``<|im_start|>role\\ncontent<|im_end|>\\n``), the
        token representation of a message does not depend on the content
        of preceding messages — only on its own role and content.  The
        stub therefore produces the same delta as the real prefix would.
        """
        # Stub: minimal prior turn to close the previous assistant response
        # structurally.  The null-byte content is a safe, unambiguous placeholder.
        stub: list[dict] = [
            {"role": "user", "content": "\x00"},
            {"role": "assistant", "content": "\x00"},
        ]

        # Tools only affect the system section, not per-message tokens.
        # Do not pass them here to keep the delta free of tool-list overhead.
        stub_ids: list[int] = list(self.tokenizer.apply_chat_template(
            stub,
            tokenize=True,
            add_special_tokens=True,
            add_generation_prompt=False,
        ))
        extended_ids: list[int] = self.tokenizer.apply_chat_template(
            _flatten_messages(stub + new_messages),
            tokenize=True,
            add_special_tokens=True,
            add_generation_prompt=True,
        )

        # stub_ids ends with: … \x00 <|im_end|> \n
        # _accumulated_ids ends with: … <|im_end|>          (SGLang stops at the
        #   stop token; the trailing \n is never generated by the model)
        #
        # The delta must therefore START with \n so that:
        #   _accumulated_ids + delta = … <|im_end|> \n <|im_start|>user\n…
        #
        # To include that \n we trim stub_ids back to just after the last
        # <|im_end|> token, leaving the separator(s) in the delta.
        im_end_id: int = self.tokenizer.convert_tokens_to_ids("<|im_end|>")
        last_im_end = next(i for i in reversed(range(len(stub_ids))) if stub_ids[i] == im_end_id)
        return extended_ids[last_im_end + 1:]

    # ---- Verbatim forwarding for non-messages paths ----

    async def _forward(
        self, request: web.Request, path: str, body_bytes: bytes
    ) -> web.Response:
        url = f"{self.sglang_url}/{path}"
        headers = {
            k: v for k, v in request.headers.items()
            if k.lower() not in ("host", "content-length", "transfer-encoding")
        }
        async with aiohttp.ClientSession() as session:
            async with session.request(
                method=request.method,
                url=url,
                data=body_bytes,
                headers=headers,
                timeout=aiohttp.ClientTimeout(total=60),
            ) as upstream:
                resp_bytes = await upstream.read()
                resp_headers = {
                    k: v for k, v in upstream.headers.items()
                    if k.lower() not in ("content-length", "transfer-encoding")
                }
                return web.Response(
                    status=upstream.status,
                    body=resp_bytes,
                    content_type=upstream.content_type,
                    headers=resp_headers,
                )
